[project]
name = "backend-hotel"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "agathahelena", email = "agatha.helena.so@gmail.com"},
    {name = "yuriramos223", email = "gabriela.heloisa.ramos.ifc@gmail.com"},
]
dependencies = [
    "django>=5.2.3",
    "djangorestframework>=3.16.0",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
