# Generated by Django 5.2.3 on 2025-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('funcionario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('CPF', models.CharField(max_length=11)),
                ('cod', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=19)),
                ('dataNascimento', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=5)),
                ('formaPagamento', models.CharField(max_length=15)),
                ('data', models.DateField(max_length=10)),
                ('hora', models.TimeField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4)),
                ('quantidadePessoas', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntra', models.DateField()),
                ('dataSai', models.DateField()),
                ('PessoasQuantidade', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codServico', models.CharField(max_length=10)),
                ('horaServico', models.TimeField(max_length=5)),
                ('QuartoServico', models.CharField(max_length=3)),
            ],
        ),
    ]
