# Generated by Django 5.2.3 on 2025-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField()),
                ('CPF', models.CharField(max_length=11)),
                ('cod', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntra', models.DateField()),
                ('dataSai', models.DateField()),
                ('PessoasQuantidade', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codServico', models.CharField(max_length=10)),
                ('horaServico', models.TimeField(max_length=5)),
                ('QuartoServico', models.CharField(max_length=3)),
            ],
        ),
    ]
