# Generated by Django 5.2.3 on 2025-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=5)),
                ('formaPagamento', models.CharField(max_length=15)),
                ('data', models.DateField(max_length=10)),
                ('hora', models.DateTimeField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='hóspede',
            name='dataNascimento',
            field=models.DateField(max_length=10),
        ),
    ]
