# Generated by Django 5.2.3 on 2025-06-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunçãoFuncionário',
            new_name='FunçãoFuncionario',
        ),
        migrations.RenameModel(
            old_name='Hóspede',
            new_name='Hospede',
        ),
    ]
