# Generated by Django 5.2.3 on 2025-06-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_funçãofuncionário_funçãofuncionario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunçãoFuncionario',
            new_name='FuncaoFuncionario',
        ),
    ]
