# Generated by Django 5.2.3 on 2025-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_pagamento_alter_hóspede_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='hora',
            field=models.TimeField(max_length=3),
        ),
    ]
