# Generated by Django 5.2.3 on 2025-06-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_pagamento_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunçãoFuncionário',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('funcionario', models.CharField(max_length=30)),
            ],
        ),
    ]
